# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import hypervec_service_pb2 as hypervec__service__pb2
except ImportError:
    import hypervec_service_pb2 as hypervec__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hypervec_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HypervecServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/hypervec.v1.HypervecService/Health',
                request_serializer=hypervec__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/hypervec.v1.HypervecService/ListCollections',
                request_serializer=hypervec__service__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.HasCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/HasCollection',
                request_serializer=hypervec__service__pb2.HasCollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.HasCollectionResponse.FromString,
                _registered_method=True)
        self.DescribeCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/DescribeCollection',
                request_serializer=hypervec__service__pb2.DescribeCollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/CreateCollection',
                request_serializer=hypervec__service__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.DropCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/DropCollection',
                request_serializer=hypervec__service__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/hypervec.v1.HypervecService/Insert',
                request_serializer=hypervec__service__pb2.InsertRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/hypervec.v1.HypervecService/Flush',
                request_serializer=hypervec__service__pb2.CollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.LoadCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/LoadCollection',
                request_serializer=hypervec__service__pb2.CollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.CloseCollection = channel.unary_unary(
                '/hypervec.v1.HypervecService/CloseCollection',
                request_serializer=hypervec__service__pb2.CollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/hypervec.v1.HypervecService/Search',
                request_serializer=hypervec__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/hypervec.v1.HypervecService/GetVersion',
                request_serializer=hypervec__service__pb2.CollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.SyncCheck = channel.unary_unary(
                '/hypervec.v1.HypervecService/SyncCheck',
                request_serializer=hypervec__service__pb2.SyncCheckRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)
        self.DownloadIndex = channel.unary_unary(
                '/hypervec.v1.HypervecService/DownloadIndex',
                request_serializer=hypervec__service__pb2.CollectionRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.DownloadIndexResponse.FromString,
                _registered_method=True)
        self.UploadIndex = channel.unary_unary(
                '/hypervec.v1.HypervecService/UploadIndex',
                request_serializer=hypervec__service__pb2.UploadIndexRequest.SerializeToString,
                response_deserializer=hypervec__service__pb2.JsonResponse.FromString,
                _registered_method=True)


class HypervecServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HypervecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hypervec__service__pb2.HealthRequest.FromString,
                    response_serializer=hypervec__service__pb2.HealthResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=hypervec__service__pb2.ListCollectionsRequest.FromString,
                    response_serializer=hypervec__service__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'HasCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.HasCollection,
                    request_deserializer=hypervec__service__pb2.HasCollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.HasCollectionResponse.SerializeToString,
            ),
            'DescribeCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCollection,
                    request_deserializer=hypervec__service__pb2.DescribeCollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=hypervec__service__pb2.CreateCollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=hypervec__service__pb2.DropCollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=hypervec__service__pb2.InsertRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=hypervec__service__pb2.CollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'LoadCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCollection,
                    request_deserializer=hypervec__service__pb2.CollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'CloseCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCollection,
                    request_deserializer=hypervec__service__pb2.CollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=hypervec__service__pb2.SearchRequest.FromString,
                    response_serializer=hypervec__service__pb2.SearchResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=hypervec__service__pb2.CollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'SyncCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncCheck,
                    request_deserializer=hypervec__service__pb2.SyncCheckRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
            'DownloadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadIndex,
                    request_deserializer=hypervec__service__pb2.CollectionRequest.FromString,
                    response_serializer=hypervec__service__pb2.DownloadIndexResponse.SerializeToString,
            ),
            'UploadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadIndex,
                    request_deserializer=hypervec__service__pb2.UploadIndexRequest.FromString,
                    response_serializer=hypervec__service__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypervec.v1.HypervecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hypervec.v1.HypervecService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HypervecService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/Health',
            hypervec__service__pb2.HealthRequest.SerializeToString,
            hypervec__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/ListCollections',
            hypervec__service__pb2.ListCollectionsRequest.SerializeToString,
            hypervec__service__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/HasCollection',
            hypervec__service__pb2.HasCollectionRequest.SerializeToString,
            hypervec__service__pb2.HasCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/DescribeCollection',
            hypervec__service__pb2.DescribeCollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/CreateCollection',
            hypervec__service__pb2.CreateCollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/DropCollection',
            hypervec__service__pb2.DropCollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/Insert',
            hypervec__service__pb2.InsertRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/Flush',
            hypervec__service__pb2.CollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/LoadCollection',
            hypervec__service__pb2.CollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/CloseCollection',
            hypervec__service__pb2.CollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/Search',
            hypervec__service__pb2.SearchRequest.SerializeToString,
            hypervec__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/GetVersion',
            hypervec__service__pb2.CollectionRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/SyncCheck',
            hypervec__service__pb2.SyncCheckRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/DownloadIndex',
            hypervec__service__pb2.CollectionRequest.SerializeToString,
            hypervec__service__pb2.DownloadIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypervec.v1.HypervecService/UploadIndex',
            hypervec__service__pb2.UploadIndexRequest.SerializeToString,
            hypervec__service__pb2.JsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
