# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _swighypervec
else:
    import _swighypervec

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


kMetricInnerProduct = _swighypervec.kMetricInnerProduct
kMetricL2 = _swighypervec.kMetricL2
kMetricL1 = _swighypervec.kMetricL1
kMetricLinf = _swighypervec.kMetricLinf
kMetricLp = _swighypervec.kMetricLp
kMetricCanberra = _swighypervec.kMetricCanberra
kMetricBrayCurtis = _swighypervec.kMetricBrayCurtis
kMetricJensenShannon = _swighypervec.kMetricJensenShannon
kMetricJaccard = _swighypervec.kMetricJaccard
kMetricNaNEuclidean = _swighypervec.kMetricNaNEuclidean
kMetricGower = _swighypervec.kMetricGower
class Index(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    d = property(_swighypervec.Index_d_get, _swighypervec.Index_d_set)
    n_total = property(_swighypervec.Index_n_total_get, _swighypervec.Index_n_total_set)
    is_trained = property(_swighypervec.Index_is_trained_get, _swighypervec.Index_is_trained_set)
    metric_type = property(_swighypervec.Index_metric_type_get, _swighypervec.Index_metric_type_set)
    __swig_destroy__ = _swighypervec.delete_Index

    def Train(self, x):
        return _swighypervec.Index_Train(self, x)

    def Add(self, x):
        return _swighypervec.Index_Add(self, x)

    def Search(self, x, k):
        return _swighypervec.Index_Search(self, x, k)

# Register Index in _swighypervec:
_swighypervec.Index_swigregister(Index)

class IndexFlatIP(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, d):
        _swighypervec.IndexFlatIP_swiginit(self, _swighypervec.new_IndexFlatIP(d))
    __swig_destroy__ = _swighypervec.delete_IndexFlatIP

# Register IndexFlatIP in _swighypervec:
_swighypervec.IndexFlatIP_swigregister(IndexFlatIP)

class IndexFlatL2(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, d):
        _swighypervec.IndexFlatL2_swiginit(self, _swighypervec.new_IndexFlatL2(d))
    __swig_destroy__ = _swighypervec.delete_IndexFlatL2

# Register IndexFlatL2 in _swighypervec:
_swighypervec.IndexFlatL2_swigregister(IndexFlatL2)

class IndexHNSWFlat(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _swighypervec.IndexHNSWFlat_swiginit(self, _swighypervec.new_IndexHNSWFlat(*args))
    __swig_destroy__ = _swighypervec.delete_IndexHNSWFlat

# Register IndexHNSWFlat in _swighypervec:
_swighypervec.IndexHNSWFlat_swigregister(IndexHNSWFlat)

class IndexLVQ(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _swighypervec.IndexLVQ_swiginit(self, _swighypervec.new_IndexLVQ(*args))
    __swig_destroy__ = _swighypervec.delete_IndexLVQ

# Register IndexLVQ in _swighypervec:
_swighypervec.IndexLVQ_swigregister(IndexLVQ)

class IndexIVFLVQ(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _swighypervec.IndexIVFLVQ_swiginit(self, _swighypervec.new_IndexIVFLVQ(*args))
    __swig_destroy__ = _swighypervec.delete_IndexIVFLVQ

# Register IndexIVFLVQ in _swighypervec:
_swighypervec.IndexIVFLVQ_swigregister(IndexIVFLVQ)

class IndexHNSWLVQ(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _swighypervec.IndexHNSWLVQ_swiginit(self, _swighypervec.new_IndexHNSWLVQ(*args))
    __swig_destroy__ = _swighypervec.delete_IndexHNSWLVQ

# Register IndexHNSWLVQ in _swighypervec:
_swighypervec.IndexHNSWLVQ_swigregister(IndexHNSWLVQ)


def WriteIndex(idx, fname, io_flags=0):
    return _swighypervec.WriteIndex(idx, fname, io_flags)

def ReadIndex(fname, io_flags=0):
    return _swighypervec.ReadIndex(fname, io_flags)

read_index = ReadIndex
write_index = WriteIndex



